In [1]:
import json
import numpy as np
from activation_functions import Tanh
from mse import mse, mse_derivative
from mlp import Dense, train, predict
from utils import get_config_params, get_data, get_training_amount, PERCEPTRON_TYPES
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
with open('./config.json', 'r') as f:
    config = json.load(f)

perceptron_type, learning_rate, training_percentage, max_epochs, bias, beta, epsilon = get_config_params(config)

input_data, expected_data = get_data()
training_amount = get_training_amount(len(input_data), training_percentage)

training_set = input_data[:training_amount]
training_expected = expected_data[:training_amount]
testing_set =  np.reshape(input_data[training_amount:], (len(input_data)-training_amount, 5, 1))
testing_expected = expected_data[training_amount:]
X = np.reshape(training_set, (training_amount, 5, 1))
Y = np.reshape(training_expected, (training_amount, 1, 1))
print(X)
print(Y)

[[[0]
  [1]
  [1]
  [1]
  [0]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[1]
  [0]
  [0]
  [1]
  [1]]

 [[1]
  [0]
  [1]
  [0]
  [1]]

 [[1]
  [1]
  [0]
  [0]
  [1]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [1]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [1]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [1]
  [1]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [1]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[0]
  [0]
  [0]
  [1]
  [0]]

 [[0]
  [0]
  [1]
  [1]
  [0]]

 [[0]
  [1]
  [0]
  [1]
  [0]]

 [[1]
  

In [9]:
network = [
        Dense(5, 6),
        Tanh(),
        Dense(6, 1),
        Tanh()
    ]
network


In [10]:
# train
train(network, mse, mse_derivative, X, Y, epochs=10000, learning_rate=0.1)

1/10000, error=0.13844255107457756
2/10000, error=0.0713386751497232
3/10000, error=0.033141459686324024
4/10000, error=0.01757992112974949
5/10000, error=0.012704888982687236
6/10000, error=0.009597459649209574
7/10000, error=0.007314875478827673
8/10000, error=0.005578424162333068
9/10000, error=0.004247181790922191
10/10000, error=0.003231958994537838
11/10000, error=0.00246339149192423
12/10000, error=0.0018841007944144295
13/10000, error=0.0014477722139159845
14/10000, error=0.0011184276963116832
15/10000, error=0.000868900250175826
16/10000, error=0.0006789981519527538
17/10000, error=0.0005338051135322143
18/10000, error=0.0004222988791198501
19/10000, error=0.0003363030288167586
20/10000, error=0.0002697189052345195
21/10000, error=0.00021797108272709014
22/10000, error=0.00017760803441237057
23/10000, error=0.00014601327648246885
24/10000, error=0.00012119479662679287
25/10000, error=0.00010163022774561397
26/10000, error=8.615209929285364e-05
27/10000, error=7.386221583320997

In [12]:
points = []
for x in testing_set:
    for y in testing_expected:
        z = predict(network, [x])
        points.append([x, y, z[0,0]])
for point in points:
    print(f"Input: {point[0]} Expected:{point[1]} Result:{point[2]}")

Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:1 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:1 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:1 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:1 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:1 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:1 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:1 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:1 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:[-0.03011214]
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:[-0.03011214]
Input: [[1]
 [0]
 [0]
 [0]
 [1]] Expected:0 Result:[0.99682045]
Input: [[1]
 [0]
 [0]
 [0]