In [1]:
import json
import numpy as np
from activation_functions import Tanh
from mse import mse, mse_derivative
from mlp import Dense, train, predict
from utils import get_config_params, get_data, get_training_amount, PERCEPTRON_TYPES
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
with open('./config.json', 'r') as f:
    config = json.load(f)

perceptron_type, learning_rate, training_percentage, max_epochs, bias, beta, epsilon = get_config_params(config)

input_data, expected_data = get_data()
training_amount = get_training_amount(len(input_data), training_percentage)

training_set = input_data[:training_amount]
training_expected = expected_data[:training_amount]
testing_set =  np.reshape(input_data[training_amount:], (len(input_data)-training_amount, 5, 1))
testing_expected = expected_data[training_amount:]
X = np.reshape(training_set, (training_amount, 5, 1))
Y = np.reshape(training_expected, (training_amount, 1, 1))
print(X)
print(Y)

[[[0]
  [1]
  [1]
  [1]
  [0]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[1]
  [0]
  [0]
  [1]
  [1]]

 [[1]
  [0]
  [1]
  [0]
  [1]]

 [[1]
  [1]
  [0]
  [0]
  [1]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [1]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [0]
  [1]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [1]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [1]
  [1]
  [1]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [0]
  [1]
  [1]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [1]]

 [[1]
  [0]
  [0]
  [0]
  [1]]

 [[0]
  [1]
  [1]
  [1]
  [0]]

 [[0]
  [0]
  [0]
  [1]
  [0]]

 [[0]
  [0]
  [1]
  [1]
  [0]]

 [[0]
  [1]
  [0]
  [1]
  [0]]

 [[1]
  

In [9]:
network = [
        Dense(5, 6),
        Tanh(),
        Dense(6, 1),
        Tanh()
    ]
network


In [21]:
# train
train(network, mse, mse_derivative, X, Y, epochs=10000, learning_rate=0.01)

1/10000, error=2.1293472979448696e-07
2/10000, error=2.129327529816226e-07
3/10000, error=2.1293077620529405e-07
4/10000, error=2.1292879946548386e-07
5/10000, error=2.1292682276217361e-07
6/10000, error=2.129248460954133e-07
7/10000, error=2.1292286946514868e-07
8/10000, error=2.1292089287141062e-07
9/10000, error=2.1291891631417737e-07
10/10000, error=2.1291693979346888e-07
11/10000, error=2.1291496330927364e-07
12/10000, error=2.1291298686159177e-07
13/10000, error=2.1291101045041808e-07
14/10000, error=2.1290903407576118e-07
15/10000, error=2.12907057737603e-07
16/10000, error=2.129050814359588e-07
17/10000, error=2.1290310517081544e-07
18/10000, error=2.1290112894219257e-07
19/10000, error=2.1289915275006533e-07
20/10000, error=2.1289717659445173e-07
21/10000, error=2.1289520047533015e-07
22/10000, error=2.1289322439271334e-07
23/10000, error=2.1289124834659762e-07
24/10000, error=2.1288927233699569e-07
25/10000, error=2.128872963638845e-07
26/10000, error=2.1288532042726273e-07
2

In [23]:
points = []
for i in range(len(testing_set)):
    z = predict(network, testing_set[i])
    points.append([testing_set[i], testing_expected[i], z[0,0]])
for point in points:
    print(f"Input: {point[0]} Expected:{point[1]} Result:{round(point[2])}")

Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:0
Input: [[1]
 [0]
 [0]
 [0]
 [1]] Expected:1 Result:1
Input: [[1]
 [0]
 [0]
 [0]
 [1]] Expected:1 Result:1
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:0
Input: [[1]
 [0]
 [0]
 [0]
 [1]] Expected:1 Result:1
Input: [[1]
 [0]
 [0]
 [0]
 [1]] Expected:1 Result:1
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:0
Input: [[0]
 [1]
 [1]
 [1]
 [0]] Expected:0 Result:0
Input: [[1]
 [0]
 [0]
 [0]
 [1]] Expected:1 Result:1
Input: [[1]
 [0]
 [0]
 [0]
 [1]] Expected:1 Result:1
Input: [[0]
 [1]
 [1]
 [1]
 [1]] Expected:1 Result:1
Input: [[0]
 [0]
 [0]
 [0]
 [1]] Expected:1 Result:1
Input: [[0]
 [0]
 [0]
 [1]
 [0]] Expected:0 Result:0
Input: [[0]
 [1]
 [1]
 [0]
 [0]] Expected:0 Result:0
